tei_generator.TEIGenerator Class Reference
Public Member Functions
__init__ (self)
Element generate_tei_header (self, Dict[str, Any] site_metadata)
Element generate_text_body (self, Dict[str, Any] pages)
str generate_tei_document (self, Dict[str, Any] site_ast)
None save_tei_document (self, str tei_xml, Union[str, Path] output_path)
Public Attributes
str tei_ns = "http://www.tei-c.org/ns/1.0"
str xml_ns = "http://www.w3.org/XML/1998/namespace"
dict ns_map = {"tei": self.tei_ns, "xml": self.xml_ns}
Protected Member Functions
Element _convert_page_to_tei_div (self, str url, Dict[str, Any] page_info)
Element _convert_ast_to_tei (self, Union[ASTNode, Dict] ast_node)
str _create_page_id (self, str url)
Detailed Description
Generate TEI XML from AST and site data
Definition at line 24 of file tei_generator.py.
Constructor & Destructor Documentation
__init__()
tei_generator.TEIGenerator.__init__ (self)
Definition at line 27 of file tei_generator.py.
Member Function Documentation
_convert_ast_to_tei()
 Element tei_generator.TEIGenerator._convert_ast_to_tei (self, Union[ASTNode, Dict] ast_node) [protected]
Convert AST node to TEI XML
Definition at line 236 of file tei_generator.py.
References _convert_ast_to_tei().
Referenced by _convert_ast_to_tei(), and _convert_page_to_tei_div().
_convert_page_to_tei_div()
 Element tei_generator.TEIGenerator._convert_page_to_tei_div (self, str url, Dict[str, Any] page_info) [protected]
Convert a single page to TEI div
Definition at line 146 of file tei_generator.py.
References _convert_ast_to_tei(), and _create_page_id().
Referenced by generate_text_body().
_create_page_id()
 str tei_generator.TEIGenerator._create_page_id (self, str url) [protected]
Create valid TEI XML ID from URL
Definition at line 426 of file tei_generator.py.
Referenced by _convert_page_to_tei_div().
generate_tei_document()
 str tei_generator.TEIGenerator.generate_tei_document (self, Dict[str, Any] site_ast)
Generate complete TEI XML document
Definition at line 434 of file tei_generator.py.
References generate_tei_header(), and generate_text_body().
generate_tei_header()
 Element tei_generator.TEIGenerator.generate_tei_header (self, Dict[str, Any] site_metadata)
Generate TEI header with site metadata
Definition at line 34 of file tei_generator.py.
Referenced by generate_tei_document().
generate_text_body()
 Element tei_generator.TEIGenerator.generate_text_body (self, Dict[str, Any] pages)
Generate TEI text body from page content
Definition at line 110 of file tei_generator.py.
References _convert_page_to_tei_div().
Referenced by generate_tei_document().
save_tei_document()
 None tei_generator.TEIGenerator.save_tei_document (self, str tei_xml, Union[str, Path] output_path)
Save TEI XML document to file
Definition at line 494 of file tei_generator.py.
Member Data Documentation
ns_map
dict tei_generator.TEIGenerator.ns_map = {"tei": self.tei_ns, "xml": self.xml_ns}
Definition at line 32 of file tei_generator.py.
tei_ns
str tei_generator.TEIGenerator.tei_ns = "http://www.tei-c.org/ns/1.0"
Definition at line 28 of file tei_generator.py.
xml_ns
str tei_generator.TEIGenerator.xml_ns = "http://www.w3.org/XML/1998/namespace"
Definition at line 29 of file tei_generator.py.
The documentation for this class was generated from the following file:
/home/domini/src/Magazine/Magazine/scripts/tei_generator.py