extract_bibliography Namespace Reference
Functions
extract_citations_from_latex (latex_file)
find_context_info (latex_file, author_name)
create_bibtex_entry (citation_key, latex_file)
process_article (article_dir)
update_master_bibliography ()
main ()
Detailed Description
Bibliography Extractor for Integral Philosophy Publishing System

This script extracts citations from LaTeX files and generates bibliography files.
It can extract citations from all articles and create individual .bib files for each article.
Function Documentation
create_bibtex_entry()
extract_bibliography.create_bibtex_entry (citation_key, latex_file)
Create a BibTeX entry for a citation based on context analysis.

Args:
    citation_key (str): The citation key
    latex_file (Path): Path to the LaTeX file

Returns:
    str: BibTeX entry or None if not enough information
Definition at line 115 of file extract_bibliography.py.
References find_context_info().
Referenced by process_article().
extract_citations_from_latex()
extract_bibliography.extract_citations_from_latex (latex_file)
Extract all citation keys from a LaTeX file.

Args:
    latex_file (Path): Path to the LaTeX file

Returns:
    set: Set of citation keys found in the file
Definition at line 16 of file extract_bibliography.py.
Referenced by process_article().
find_context_info()
extract_bibliography.find_context_info (latex_file, author_name)
Find context information for an author in the text.

Args:
    latex_file (Path): Path to the LaTeX file
    author_name (str): Author name to search for

Returns:
    dict: Context information including year, title, etc.
Definition at line 66 of file extract_bibliography.py.
Referenced by create_bibtex_entry().
main()
extract_bibliography.main ()
Main function to handle command line arguments and run extraction.
Definition at line 283 of file extract_bibliography.py.
References main(), process_article(), and update_master_bibliography().
Referenced by main().
process_article()
extract_bibliography.process_article (article_dir)
Process a single article and generate its bibliography file.

Args:
    article_dir (Path): Path to the article directory

Returns:
    int: Number of citations processed
Definition at line 178 of file extract_bibliography.py.
References create_bibtex_entry(), and extract_citations_from_latex().
Referenced by main().
update_master_bibliography()
extract_bibliography.update_master_bibliography ()
Update the master bibliography from all individual article bibliographies.
Definition at line 239 of file extract_bibliography.py.
Referenced by main().