validate_publication Namespace Reference
Functions
validate_publication_outputs ()
main ()
Detailed Description
Integration script for validation system with Integral Philosophy publishing pipeline.
Demonstrates end-to-end validation of publication outputs.
Function Documentation
main()
validate_publication.main ()
Run publication validation.
Definition at line 240 of file validate_publication.py.
References main(), and validate_publication_outputs().
Referenced by main().
validate_publication_outputs()
validate_publication.validate_publication_outputs ()
Validate typical publication outputs from the Integral Philosophy system.
Definition at line 26 of file validate_publication.py.
Referenced by main().