generate_docs Namespace Reference
Functions
run_command (cmd, description="")
generate_api_docs ()
generate_user_docs ()
generate_dev_docs ()
main ()
Function Documentation
generate_api_docs()
generate_docs.generate_api_docs ()
Generate API documentation using Doxygen.
Definition at line 29 of file generate_docs.py.
References run_command().
Referenced by main().
generate_dev_docs()
generate_docs.generate_dev_docs ()
Generate development documentation.
Definition at line 65 of file generate_docs.py.
Referenced by main().
generate_user_docs()
generate_docs.generate_user_docs ()
Generate user documentation from markdown files.
Definition at line 45 of file generate_docs.py.
Referenced by main().
main()
generate_docs.main ()
Main function.
Definition at line 157 of file generate_docs.py.
References generate_api_docs(), generate_dev_docs(), generate_user_docs(), and main().
Referenced by main().
run_command()
generate_docs.run_command (cmd, description = "")
Run a command with error handling.
Definition at line 12 of file generate_docs.py.
Referenced by generate_api_docs().