advanced_reconstruction.AdvancedTeXReconstructor Class Reference
Public Member Functions
__init__ (self)
Dict extract_full_content (self, Path filepath)
str reconstruct_to_markdown (self, Dict article_data)
Public Attributes
dict content_cache = {}
Protected Member Functions
Dict _parse_conditional_article (self, str content, Path filepath)
Dict _parse_standard_article (self, str content, Path filepath)
str _extract_title (self, str content)
str _extract_author (self, str content)
List[Dict] _extract_all_sections (self, str content)
List[Dict] _extract_math_content (self, str content)
Dict _extract_keywords (self, str content)
str _clean_latex (self, str text)
str _extract_text_content (self, str latex_text)
Detailed Description
Advanced reconstruction tool with better content parsing.
Definition at line 15 of file advanced_reconstruction.py.
Constructor & Destructor Documentation
__init__()
advanced_reconstruction.AdvancedTeXReconstructor.__init__ (self)
Definition at line 18 of file advanced_reconstruction.py.
Member Function Documentation
_clean_latex()
 str advanced_reconstruction.AdvancedTeXReconstructor._clean_latex (self, str text) [protected]
Clean LaTeX commands while preserving structure.
Definition at line 199 of file advanced_reconstruction.py.
Referenced by _extract_text_content(), _parse_conditional_article(), and _parse_standard_article().
_extract_all_sections()
 List[Dict] advanced_reconstruction.AdvancedTeXReconstructor._extract_all_sections (self, str content) [protected]
Extract all sections with hierarchy.
Definition at line 121 of file advanced_reconstruction.py.
Referenced by _parse_conditional_article(), and _parse_standard_article().
_extract_author()
 str advanced_reconstruction.AdvancedTeXReconstructor._extract_author (self, str content) [protected]
Extract author name.
Definition at line 105 of file advanced_reconstruction.py.
Referenced by _parse_conditional_article(), and _parse_standard_article().
_extract_keywords()
 Dict advanced_reconstruction.AdvancedTeXReconstructor._extract_keywords (self, str content) [protected]
Extract keywords in multiple languages.
Definition at line 181 of file advanced_reconstruction.py.
Referenced by _parse_conditional_article(), and _parse_standard_article().
_extract_math_content()
 List[Dict] advanced_reconstruction.AdvancedTeXReconstructor._extract_math_content (self, str content) [protected]
Extract mathematical expressions.
Definition at line 153 of file advanced_reconstruction.py.
Referenced by _parse_conditional_article(), and _parse_standard_article().
_extract_text_content()
 str advanced_reconstruction.AdvancedTeXReconstructor._extract_text_content (self, str latex_text) [protected]
Extract readable text from LaTeX content.
Definition at line 311 of file advanced_reconstruction.py.
References _clean_latex().
Referenced by markdowntex_parser.MarkdownTeXParser._extract_text_content(), markdowntex_parser.MarkdownTeXParser.extract_links(), and reconstruct_to_markdown().
_extract_title()
 str advanced_reconstruction.AdvancedTeXReconstructor._extract_title (self, str content) [protected]
Extract article title.
Definition at line 85 of file advanced_reconstruction.py.
Referenced by _parse_conditional_article(), and _parse_standard_article().
_parse_conditional_article()
 Dict advanced_reconstruction.AdvancedTeXReconstructor._parse_conditional_article (self, str content, Path filepath) [protected]
Parse articles with conditional content (English/Russian).
Definition at line 39 of file advanced_reconstruction.py.
References _clean_latex(), _extract_all_sections(), _extract_author(), _extract_keywords(), _extract_math_content(), and _extract_title().
Referenced by extract_full_content().
_parse_standard_article()
 Dict advanced_reconstruction.AdvancedTeXReconstructor._parse_standard_article (self, str content, Path filepath) [protected]
Parse standard LaTeX articles.
Definition at line 72 of file advanced_reconstruction.py.
References _clean_latex(), _extract_all_sections(), _extract_author(), _extract_keywords(), _extract_math_content(), and _extract_title().
Referenced by extract_full_content().
extract_full_content()
 Dict advanced_reconstruction.AdvancedTeXReconstructor.extract_full_content (self, Path filepath)
Extract and reconstruct full content from article files.
Definition at line 21 of file advanced_reconstruction.py.
References _parse_conditional_article(), and _parse_standard_article().
reconstruct_to_markdown()
 str advanced_reconstruction.AdvancedTeXReconstructor.reconstruct_to_markdown (self, Dict article_data)
Reconstruct article data to comprehensive markdown.
Definition at line 216 of file advanced_reconstruction.py.
References _extract_text_content().
Member Data Documentation
content_cache
dict advanced_reconstruction.AdvancedTeXReconstructor.content_cache = {}
Definition at line 19 of file advanced_reconstruction.py.
The documentation for this class was generated from the following file:
/home/domini/src/Magazine/Magazine/scripts/advanced_reconstruction.py