graph TD\n\n%% Site Structure: https://example.com\n\nclassDef information fill:#00BCD4,stroke:#333,stroke-width:2px\nclassDef page fill:#757575,stroke:#333,stroke-width:2px\n\nexample_com["example.com"]:::page\nexample_com_about["about"]:::information\nexample_com_contact["contact"]:::information\n\nexample_com --> |link| example_com_about\nexample_com --> |link| example_com_contact\nexample_com_about --> |link| example_com\nexample_com_contact --> |link| example_com