web_scraper.WebScraper Class Reference
Public Member Functions
__init__ (self, str base_url, str output_dir="scraped_content", float delay=1.0)
bool setup_driver (self)
bool wait_for_page_load (self, int timeout=10)
List[str] extract_links (self)
bool is_same_domain (self, str url)
Dict extract_content (self)
str get_main_content (self)
str html_to_markdowntex (self, str html_content)
str convert_list (self, str list_html, str list_type)
bool save_page (self, str url, Dict content)
bool scrape_page (self, str url)
None recursive_scrape (self, int max_pages=1000, int max_depth=10)
None generate_sitemap (self)
Public Attributes
base_url = base_url
domain = urlparse(base_url).netloc
output_dir = Path(output_dir)
delay = delay
Set[str] visited_urls = set()
Set[str] downloaded_urls = set()
Set[str] failed_urls = set()
driver = None
dict site_ast
Detailed Description
Recursive web scraper with JavaScript processing and MarkdownTeX output
Definition at line 33 of file web_scraper.py.
Constructor & Destructor Documentation
__init__()
web_scraper.WebScraper.__init__ (self, str base_url, str output_dir = "scraped_content", float delay = 1.0)
Definition at line 36 of file web_scraper.py.
Member Function Documentation
convert_list()
 str web_scraper.WebScraper.convert_list (self, str list_html, str list_type)
Convert HTML lists to Markdown
Definition at line 302 of file web_scraper.py.
Referenced by html_to_markdowntex().
extract_content()
 Dict web_scraper.WebScraper.extract_content (self)
Extract content from current page and convert to MarkdownTeX
Definition at line 160 of file web_scraper.py.
References driver, get_main_content(), and html_to_markdowntex().
Referenced by scrape_page().
extract_links()
 List[str] web_scraper.WebScraper.extract_links (self)
Extract all links from current page
Definition at line 118 of file web_scraper.py.
References driver, is_same_domain(), and visited_urls.
Referenced by scrape_page().
generate_sitemap()
 None web_scraper.WebScraper.generate_sitemap (self)
Generate sitemap of scraped pages
Definition at line 441 of file web_scraper.py.
References downloaded_urls, and output_dir.
get_main_content()
 str web_scraper.WebScraper.get_main_content (self)
Extract main content from page
Definition at line 218 of file web_scraper.py.
References driver.
Referenced by extract_content().
html_to_markdowntex()
 str web_scraper.WebScraper.html_to_markdowntex (self, str html_content)
Convert HTML to MarkdownTeX preserving structure and links
Definition at line 249 of file web_scraper.py.
References convert_list().
Referenced by extract_content().
is_same_domain()
 bool web_scraper.WebScraper.is_same_domain (self, str url)
Check if URL belongs to the same domain
Definition at line 152 of file web_scraper.py.
References domain.
Referenced by extract_links().
recursive_scrape()
 None web_scraper.WebScraper.recursive_scrape (self, int max_pages = 1000, int max_depth = 10)
Recursively scrape entire website
Definition at line 392 of file web_scraper.py.
References base_url, downloaded_urls, driver, failed_urls, output_dir, scrape_page(), setup_driver(), site_ast, and visited_urls.
save_page()
 bool web_scraper.WebScraper.save_page (self, str url, Dict content)
Save page content to file
Definition at line 313 of file web_scraper.py.
References output_dir, and site_ast.
Referenced by scrape_page().
scrape_page()
 bool web_scraper.WebScraper.scrape_page (self, str url)
Scrape a single page
Definition at line 353 of file web_scraper.py.
References delay, downloaded_urls, driver, extract_content(), markdowntex_parser.MarkdownTeXParser.extract_links(), extract_links(), failed_urls, save_page(), site_ast, and wait_for_page_load().
Referenced by recursive_scrape().
setup_driver()
 bool web_scraper.WebScraper.setup_driver (self)
Initialize Chrome WebDriver with options
Definition at line 64 of file web_scraper.py.
References driver.
Referenced by recursive_scrape().
wait_for_page_load()
 bool web_scraper.WebScraper.wait_for_page_load (self, int timeout = 10)
Wait for page to fully load including JavaScript
Definition at line 89 of file web_scraper.py.
References driver.
Referenced by scrape_page().
Member Data Documentation
base_url
web_scraper.WebScraper.base_url = base_url
Definition at line 39 of file web_scraper.py.
Referenced by recursive_scrape().
delay
web_scraper.WebScraper.delay = delay
Definition at line 42 of file web_scraper.py.
Referenced by scrape_page().
domain
web_scraper.WebScraper.domain = urlparse(base_url).netloc
Definition at line 40 of file web_scraper.py.
Referenced by is_same_domain().
downloaded_urls
web_scraper.WebScraper.downloaded_urls = set()
Definition at line 44 of file web_scraper.py.
Referenced by generate_sitemap(), recursive_scrape(), and scrape_page().
driver
web_scraper.WebScraper.driver = None
Definition at line 46 of file web_scraper.py.
Referenced by extract_content(), extract_links(), get_main_content(), recursive_scrape(), scrape_page(), setup_driver(), and wait_for_page_load().
failed_urls
Set[str] web_scraper.WebScraper.failed_urls = set()
Definition at line 45 of file web_scraper.py.
Referenced by recursive_scrape(), and scrape_page().
output_dir
web_scraper.WebScraper.output_dir = Path(output_dir)
Definition at line 41 of file web_scraper.py.
Referenced by generate_sitemap(), recursive_scrape(), and save_page().
site_ast
web_scraper.WebScraper.site_ast
Initial value:
= {
            "pages": {},
            "links": {},
            "metadata": {
                "base_url": base_url,
                "domain": self.domain,
                "scraped_at": time.strftime("%Y-%m-%d %H:%M:%S"),
                "total_pages": 0,
            },
        }
Definition at line 47 of file web_scraper.py.
Referenced by recursive_scrape(), save_page(), and scrape_page().
visited_urls
Set[str] web_scraper.WebScraper.visited_urls = set()
Definition at line 43 of file web_scraper.py.
Referenced by extract_links(), and recursive_scrape().
The documentation for this class was generated from the following file:
/home/domini/src/Magazine/Magazine/scripts/web_scraper.py