latex_to_markdown.TeXAnalyzer Class Reference
Public Member Functions
__init__ (self)
Dict analyze_file (self, Path filepath)
str reconstruct_markdown_tex (self, Dict analysis)
Public Attributes
dict content_map = {}
dict structure_map = {}
dict math_content = {}
dict metadata = {}
Protected Member Functions
str _classify_file (self, Path filepath, str content)
List[Dict] _extract_sections (self, str content)
List[Dict] _extract_math (self, str content)
List[str] _extract_citations (self, str content)
List[Dict] _extract_tables (self, str content)
List[Dict] _extract_figures (self, str content)
List[str] _detect_languages (self, str content)
Dict _analyze_structure (self, str content)
str _reconstruct_article (self, Dict analysis)
str _reconstruct_config (self, Dict analysis)
str _reconstruct_frontmatter (self, Dict analysis)
str _reconstruct_main (self, Dict analysis)
str _reconstruct_generic (self, Dict analysis)
Detailed Description
Analyzes LaTeX files and reconstructs markdown+TeX source.
Definition at line 15 of file latex_to_markdown.py.
Constructor & Destructor Documentation
__init__()
latex_to_markdown.TeXAnalyzer.__init__ (self)
Definition at line 18 of file latex_to_markdown.py.
Member Function Documentation
_analyze_structure()
 Dict latex_to_markdown.TeXAnalyzer._analyze_structure (self, str content) [protected]
Analyze document structure.
Definition at line 191 of file latex_to_markdown.py.
Referenced by analyze_file().
_classify_file()
 str latex_to_markdown.TeXAnalyzer._classify_file (self, Path filepath, str content) [protected]
Classify file type based on path and content.
Definition at line 51 of file latex_to_markdown.py.
Referenced by analyze_file().
_detect_languages()
 List[str] latex_to_markdown.TeXAnalyzer._detect_languages (self, str content) [protected]
Detect content languages.
Definition at line 171 of file latex_to_markdown.py.
Referenced by analyze_file().
_extract_citations()
 List[str] latex_to_markdown.TeXAnalyzer._extract_citations (self, str content) [protected]
Extract bibliographic citations.
Definition at line 133 of file latex_to_markdown.py.
Referenced by analyze_file().
_extract_figures()
 List[Dict] latex_to_markdown.TeXAnalyzer._extract_figures (self, str content) [protected]
Extract figure references.
Definition at line 154 of file latex_to_markdown.py.
Referenced by analyze_file().
_extract_math()
 List[Dict] latex_to_markdown.TeXAnalyzer._extract_math (self, str content) [protected]
Extract mathematical content.
Definition at line 93 of file latex_to_markdown.py.
Referenced by analyze_file().
_extract_sections()
 List[Dict] latex_to_markdown.TeXAnalyzer._extract_sections (self, str content) [protected]
Extract section hierarchy.
Definition at line 75 of file latex_to_markdown.py.
Referenced by analyze_file().
_extract_tables()
 List[Dict] latex_to_markdown.TeXAnalyzer._extract_tables (self, str content) [protected]
Extract table structures.
Definition at line 144 of file latex_to_markdown.py.
Referenced by analyze_file().
_reconstruct_article()
 str latex_to_markdown.TeXAnalyzer._reconstruct_article (self, Dict analysis) [protected]
Reconstruct article content as markdown+TeX.
Definition at line 226 of file latex_to_markdown.py.
Referenced by reconstruct_markdown_tex().
_reconstruct_config()
 str latex_to_markdown.TeXAnalyzer._reconstruct_config (self, Dict analysis) [protected]
Reconstruct configuration as commented LaTeX.
Definition at line 281 of file latex_to_markdown.py.
Referenced by reconstruct_markdown_tex().
_reconstruct_frontmatter()
 str latex_to_markdown.TeXAnalyzer._reconstruct_frontmatter (self, Dict analysis) [protected]
Reconstruct frontmatter content.
Definition at line 292 of file latex_to_markdown.py.
Referenced by reconstruct_markdown_tex().
_reconstruct_generic()
 str latex_to_markdown.TeXAnalyzer._reconstruct_generic (self, Dict analysis) [protected]
Generic reconstruction for other file types.
Definition at line 315 of file latex_to_markdown.py.
Referenced by reconstruct_markdown_tex().
_reconstruct_main()
 str latex_to_markdown.TeXAnalyzer._reconstruct_main (self, Dict analysis) [protected]
Reconstruct main document structure.
Definition at line 298 of file latex_to_markdown.py.
Referenced by reconstruct_markdown_tex().
analyze_file()
 Dict latex_to_markdown.TeXAnalyzer.analyze_file (self, Path filepath)
Analyze individual LaTeX file.
Definition at line 24 of file latex_to_markdown.py.
References _analyze_structure(), _classify_file(), _detect_languages(), _extract_citations(), _extract_figures(), _extract_math(), _extract_sections(), and _extract_tables().
reconstruct_markdown_tex()
 str latex_to_markdown.TeXAnalyzer.reconstruct_markdown_tex (self, Dict analysis)
Reconstruct markdown+TeX from analysis.
Definition at line 208 of file latex_to_markdown.py.
References _reconstruct_article(), _reconstruct_config(), _reconstruct_frontmatter(), _reconstruct_generic(), and _reconstruct_main().
Member Data Documentation
content_map
dict latex_to_markdown.TeXAnalyzer.content_map = {}
Definition at line 19 of file latex_to_markdown.py.
math_content
dict latex_to_markdown.TeXAnalyzer.math_content = {}
Definition at line 21 of file latex_to_markdown.py.
metadata
dict latex_to_markdown.TeXAnalyzer.metadata = {}
Definition at line 22 of file latex_to_markdown.py.
structure_map
dict latex_to_markdown.TeXAnalyzer.structure_map = {}
Definition at line 20 of file latex_to_markdown.py.
The documentation for this class was generated from the following file:
/home/domini/src/Magazine/Magazine/scripts/latex_to_markdown.py