content_pipeline.ContentPipeline Class Reference
Public Member Functions
__init__ (self, Path work_dir=Path("content_pipeline"))
bool process_website (self, str url, int max_pages=100)
Dict[str, Any] generate_report (self)
Public Attributes
work_dir = work_dir
dict dirs
scraper = None
parser = MarkdownTeXParser()
uml_transformer = ASTToUMLTransformer()
tei_generator = TEIGenerator()
xslt_transformer = XSLTTransformer()
html_tei_converter = HTMLTEIConverter()
dict results
Protected Member Functions
bool _stage_1_scrape_website (self, str url, int max_pages)
bool _stage_2_parse_content (self)
bool _stage_3_generate_uml (self)
bool _stage_4_generate_tei (self)
bool _stage_5_transform_formats (self)
bool _stage_6_validate_pipeline (self)
Dict[str, Any] _validate_xml (self, Path xml_file)
Dict[str, Any] _validate_tei_structure (self, Path tei_file)
Dict[str, Any] _check_format_consistency (self)
int _xpath_count (self, Path xml_file, str xpath)
Dict[str, Any] _get_directory_structure (self)
List[str] _generate_recommendations (self)
Detailed Description
Master content transformation pipeline
Definition at line 43 of file content_pipeline.py.
Constructor & Destructor Documentation
__init__()
content_pipeline.ContentPipeline.__init__ (self, Path work_dir = Path("content_pipeline"))
Definition at line 46 of file content_pipeline.py.
Member Function Documentation
_check_format_consistency()
 Dict[str, Any] content_pipeline.ContentPipeline._check_format_consistency (self) [protected]
Check consistency across generated formats
Definition at line 423 of file content_pipeline.py.
References dirs.
Referenced by _stage_6_validate_pipeline().
_generate_recommendations()
 List[str] content_pipeline.ContentPipeline._generate_recommendations (self) [protected]
Generate recommendations based on pipeline results
Definition at line 514 of file content_pipeline.py.
References results.
Referenced by generate_report().
_get_directory_structure()
 Dict[str, Any] content_pipeline.ContentPipeline._get_directory_structure (self) [protected]
Get directory structure and file counts
Definition at line 497 of file content_pipeline.py.
References dirs.
Referenced by generate_report().
_stage_1_scrape_website()
 bool content_pipeline.ContentPipeline._stage_1_scrape_website (self, str url, int max_pages) [protected]
Stage 1: Scrape website content
Definition at line 132 of file content_pipeline.py.
References dirs, results, and scraper.
Referenced by process_website().
_stage_2_parse_content()
 bool content_pipeline.ContentPipeline._stage_2_parse_content (self) [protected]
Stage 2: Parse MarkdownTeX content to AST
Definition at line 165 of file content_pipeline.py.
References dirs, parser, results, and work_dir.
Referenced by process_website().
_stage_3_generate_uml()
 bool content_pipeline.ContentPipeline._stage_3_generate_uml (self) [protected]
Stage 3: Generate UML diagrams from site structure
Definition at line 229 of file content_pipeline.py.
References dirs, results, and uml_transformer.
Referenced by process_website().
_stage_4_generate_tei()
 bool content_pipeline.ContentPipeline._stage_4_generate_tei (self) [protected]
Stage 4: Generate canonical TEI XML format
Definition at line 267 of file content_pipeline.py.
References _validate_xml(), dirs, results, tei_generator, and work_dir.
Referenced by process_website().
_stage_5_transform_formats()
 bool content_pipeline.ContentPipeline._stage_5_transform_formats (self) [protected]
Stage 5: Transform TEI to multiple output formats
Definition at line 302 of file content_pipeline.py.
References dirs, results, and xslt_transformer.
Referenced by process_website().
_stage_6_validate_pipeline()
 bool content_pipeline.ContentPipeline._stage_6_validate_pipeline (self) [protected]
Stage 6: Validate pipeline and test isomorphism
Definition at line 346 of file content_pipeline.py.
References _check_format_consistency(), _validate_tei_structure(), dirs, html_tei_converter, and results.
Referenced by process_website().
_validate_tei_structure()
 Dict[str, Any] content_pipeline.ContentPipeline._validate_tei_structure (self, Path tei_file) [protected]
Validate TEI structure
Definition at line 399 of file content_pipeline.py.
References _xpath_count().
Referenced by _stage_6_validate_pipeline().
_validate_xml()
 Dict[str, Any] content_pipeline.ContentPipeline._validate_xml (self, Path xml_file) [protected]
Validate XML file
Definition at line 383 of file content_pipeline.py.
Referenced by _stage_4_generate_tei().
_xpath_count()
 int content_pipeline.ContentPipeline._xpath_count (self, Path xml_file, str xpath) [protected]
Get XPath count from XML file
Definition at line 459 of file content_pipeline.py.
Referenced by html_tei_converter.HTMLTEIConverter._compare_html_files(), and _validate_tei_structure().
generate_report()
 Dict[str, Any] content_pipeline.ContentPipeline.generate_report (self)
Generate comprehensive pipeline report
Definition at line 476 of file content_pipeline.py.
References _generate_recommendations(), _get_directory_structure(), dirs, results, and work_dir.
process_website()
 bool content_pipeline.ContentPipeline.process_website (self, str url, int max_pages = 100)
Process complete website through the pipeline
Definition at line 81 of file content_pipeline.py.
References _stage_1_scrape_website(), _stage_2_parse_content(), _stage_3_generate_uml(), _stage_4_generate_tei(), _stage_5_transform_formats(), _stage_6_validate_pipeline(), and results.
Member Data Documentation
dirs
dict content_pipeline.ContentPipeline.dirs
Initial value:
= {
            "scraped": self.work_dir / "01_scraped",
            "parsed": self.work_dir / "02_parsed",
            "uml": self.work_dir / "03_uml",
            "tei": self.work_dir / "04_tei",
            "transformed": self.work_dir / "05_transformed",
            "validation": self.work_dir / "06_validation",
            "reports": self.work_dir / "reports",
        }
Definition at line 51 of file content_pipeline.py.
Referenced by _check_format_consistency(), _get_directory_structure(), _stage_1_scrape_website(), _stage_2_parse_content(), _stage_3_generate_uml(), _stage_4_generate_tei(), _stage_5_transform_formats(), _stage_6_validate_pipeline(), and generate_report().
html_tei_converter
content_pipeline.ContentPipeline.html_tei_converter = HTMLTEIConverter()
Definition at line 70 of file content_pipeline.py.
Referenced by _stage_6_validate_pipeline().
parser
content_pipeline.ContentPipeline.parser = MarkdownTeXParser()
Definition at line 66 of file content_pipeline.py.
Referenced by _stage_2_parse_content().
results
dict content_pipeline.ContentPipeline.results
Initial value:
= {
            "start_time": None,
            "end_time": None,
            "duration": None,
            "stages": {},
            "success": False,
        }
Definition at line 73 of file content_pipeline.py.
Referenced by _generate_recommendations(), _stage_1_scrape_website(), _stage_2_parse_content(), _stage_3_generate_uml(), _stage_4_generate_tei(), _stage_5_transform_formats(), _stage_6_validate_pipeline(), generate_report(), and process_website().
scraper
content_pipeline.ContentPipeline.scraper = None
Definition at line 65 of file content_pipeline.py.
Referenced by _stage_1_scrape_website().
tei_generator
content_pipeline.ContentPipeline.tei_generator = TEIGenerator()
Definition at line 68 of file content_pipeline.py.
Referenced by _stage_4_generate_tei().
uml_transformer
content_pipeline.ContentPipeline.uml_transformer = ASTToUMLTransformer()
Definition at line 67 of file content_pipeline.py.
Referenced by _stage_3_generate_uml().
work_dir
content_pipeline.ContentPipeline.work_dir = work_dir
Definition at line 47 of file content_pipeline.py.
Referenced by html_tei_converter.HTMLTEIConverter._compare_html_files(), format_converter.FormatConverter._convert_with_pandoc(), html_tei_converter.HTMLTEIConverter._create_xslt_stylesheets(), _stage_2_parse_content(), _stage_4_generate_tei(), format_converter.FormatConverter.convert(), format_converter.FormatConverter.convert_from_ast(), format_converter.FormatConverter.convert_to_ast(), generate_report(), html_tei_converter.HTMLTEIConverter.html_to_tei(), and html_tei_converter.HTMLTEIConverter.tei_to_html().
xslt_transformer
content_pipeline.ContentPipeline.xslt_transformer = XSLTTransformer()
Definition at line 69 of file content_pipeline.py.
Referenced by _stage_5_transform_formats().
The documentation for this class was generated from the following file:
/home/domini/src/Magazine/Magazine/scripts/content_pipeline.py