ast_to_uml.ASTToUMLTransformer Class Reference
Public Member Functions
__init__ (self)
Dict[str, Any] transform_site_ast (self, Dict[str, Any] site_ast)
str generate_plantuml (self, Dict[str, Any] uml_data)
str generate_mermaid (self, Dict[str, Any] uml_data)
str generate_graphviz (self, Dict[str, Any] uml_data)
None generate_all_formats (self, Dict[str, Any] uml_data, Path output_dir)
Public Attributes
dict nodes = {}
list edges = []
dict site_structure = {}
dict page_hierarchy = {}
dict link_graph = {}
Protected Member Functions
None _create_page_node (self, str url, Dict[str, Any] page_info)
str _classify_page_type (self, str url, Dict[str, Any] metadata)
Dict[str, str] _get_page_style (self, str page_type)
None _create_link_edges (self, Dict[str, Any] pages)
None _create_hierarchy (self, Dict[str, Any] pages)
Dict[str, Any] _calculate_statistics (self)
str _sanitize_id (self, str url)
List[Dict[str, Any]] _serialize_nodes (self)
List[Dict[str, Any]] _serialize_edges (self)
Detailed Description
Transforms site AST into UML diagrams
Definition at line 59 of file ast_to_uml.py.
Constructor & Destructor Documentation
__init__()
ast_to_uml.ASTToUMLTransformer.__init__ (self)
Definition at line 62 of file ast_to_uml.py.
Member Function Documentation
_calculate_statistics()
 Dict[str, Any] ast_to_uml.ASTToUMLTransformer._calculate_statistics (self) [protected]
Calculate statistics about the site structure
Definition at line 231 of file ast_to_uml.py.
References edges, nodes, and page_hierarchy.
Referenced by transform_site_ast().
_classify_page_type()
 str ast_to_uml.ASTToUMLTransformer._classify_page_type (self, str url, Dict[str, Any] metadata) [protected]
Classify page type based on URL and metadata
Definition at line 133 of file ast_to_uml.py.
Referenced by _create_page_node().
_create_hierarchy()
 None ast_to_uml.ASTToUMLTransformer._create_hierarchy (self, Dict[str, Any] pages) [protected]
Create hierarchical structure from URL paths
Definition at line 199 of file ast_to_uml.py.
References page_hierarchy.
Referenced by transform_site_ast().
_create_link_edges()
 None ast_to_uml.ASTToUMLTransformer._create_link_edges (self, Dict[str, Any] pages) [protected]
Create edges representing links between pages
Definition at line 181 of file ast_to_uml.py.
References _sanitize_id(), and edges.
Referenced by transform_site_ast().
_create_page_node()
 None ast_to_uml.ASTToUMLTransformer._create_page_node (self, str url, Dict[str, Any] page_info) [protected]
Create UML node for a page
Definition at line 94 of file ast_to_uml.py.
References _classify_page_type(), _get_page_style(), _sanitize_id(), and nodes.
Referenced by transform_site_ast().
_get_page_style()
 Dict[str, str] ast_to_uml.ASTToUMLTransformer._get_page_style (self, str page_type) [protected]
Get styling for page type
Definition at line 167 of file ast_to_uml.py.
Referenced by _create_page_node(), and generate_mermaid().
_sanitize_id()
 str ast_to_uml.ASTToUMLTransformer._sanitize_id (self, str url) [protected]
Create a valid UML node ID from URL
Definition at line 250 of file ast_to_uml.py.
Referenced by _create_link_edges(), and _create_page_node().
_serialize_edges()
 List[Dict[str, Any]] ast_to_uml.ASTToUMLTransformer._serialize_edges (self) [protected]
Serialize edges to dictionary format
Definition at line 275 of file ast_to_uml.py.
References edges.
Referenced by transform_site_ast().
_serialize_nodes()
 List[Dict[str, Any]] ast_to_uml.ASTToUMLTransformer._serialize_nodes (self) [protected]
Serialize nodes to dictionary format
Definition at line 262 of file ast_to_uml.py.
References nodes.
Referenced by transform_site_ast().
generate_all_formats()
 None ast_to_uml.ASTToUMLTransformer.generate_all_formats (self, Dict[str, Any] uml_data, Path output_dir)
Generate all supported UML formats
Definition at line 449 of file ast_to_uml.py.
References generate_graphviz(), generate_mermaid(), and generate_plantuml().
generate_graphviz()
 str ast_to_uml.ASTToUMLTransformer.generate_graphviz (self, Dict[str, Any] uml_data)
Generate Graphviz DOT representation
Definition at line 388 of file ast_to_uml.py.
Referenced by generate_all_formats().
generate_mermaid()
 str ast_to_uml.ASTToUMLTransformer.generate_mermaid (self, Dict[str, Any] uml_data)
Generate Mermaid diagram
Definition at line 343 of file ast_to_uml.py.
References _get_page_style().
Referenced by generate_all_formats().
generate_plantuml()
 str ast_to_uml.ASTToUMLTransformer.generate_plantuml (self, Dict[str, Any] uml_data)
Generate PlantUML representation
Definition at line 287 of file ast_to_uml.py.
Referenced by generate_all_formats().
transform_site_ast()
 Dict[str, Any] ast_to_uml.ASTToUMLTransformer.transform_site_ast (self, Dict[str, Any] site_ast)
Transform entire site AST to UML representation
Definition at line 69 of file ast_to_uml.py.
References _calculate_statistics(), _create_hierarchy(), _create_link_edges(), _create_page_node(), _serialize_edges(), _serialize_nodes(), and page_hierarchy.
Member Data Documentation
edges
list ast_to_uml.ASTToUMLTransformer.edges = []
Definition at line 64 of file ast_to_uml.py.
Referenced by _calculate_statistics(), _create_link_edges(), and _serialize_edges().
link_graph
dict ast_to_uml.ASTToUMLTransformer.link_graph = {}
Definition at line 67 of file ast_to_uml.py.
nodes
ast_to_uml.ASTToUMLTransformer.nodes = {}
Definition at line 63 of file ast_to_uml.py.
Referenced by _calculate_statistics(), _create_page_node(), and _serialize_nodes().
page_hierarchy
ast_to_uml.ASTToUMLTransformer.page_hierarchy = {}
Definition at line 66 of file ast_to_uml.py.
Referenced by _calculate_statistics(), _create_hierarchy(), and transform_site_ast().
site_structure
dict ast_to_uml.ASTToUMLTransformer.site_structure = {}
Definition at line 65 of file ast_to_uml.py.
The documentation for this class was generated from the following file:
/home/domini/src/Magazine/Magazine/scripts/ast_to_uml.py