name: integral-philosophy
version: 0.1.0.0
synopsis: Integral Philosophy Publishing System
description: Enterprise-grade validation and processing for academic publications

dependencies:
- base >= 4.17 && < 5
- text >= 1.2 && < 2.2
- bytestring >= 0.11 && < 0.13
- directory >= 1.3 && < 1.4
- filepath >= 1.4 && < 1.6
- process >= 1.6 && < 1.8
- containers >= 0.6 && < 0.8
- time >= 1.9 && < 1.13
- mtl >= 2.2 && < 2.4
- transformers >= 0.5 && < 0.7
- optparse-applicative >= 0.16 && < 0.19
- split >= 0.2 && < 0.3
- deepseq >= 1.4 && < 1.5
- random >= 1.2 && < 1.3
- temporary >= 1.3 && < 1.4

language: GHC2021
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src
  exposed-modules:
  - IntegralPhilosophy.Types
  - IntegralPhilosophy.Validation
  - IntegralPhilosophy.Validation.LaTeX
  - IntegralPhilosophy.Reconstruction.LaTeX
  other-modules:
  - IntegralPhilosophy.Prelude

executables:
  integral-philosophy:
    main: Main.hs
    source-dirs: src
    dependencies:
    - base
    - text
    - bytestring
    - directory
    - filepath
    - process
    - containers
    - parsec
    - megaparsec
    - regex-tdfa
    - aeson
    - yaml
    - mtl
    - transformers
    - lens
    - optparse-applicative
    - split
    - prettyprinter
    - async
    - stm
    - vector
    - unordered-containers
    - hashable
    - time
    - deepseq
    - random
    - temporary
    ghc-options:
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-record-updates"
    - "-Wincomplete-uni-patterns"
    - "-Wmissing-export-lists"
    - "-Wmissing-home-modules"
    - "-Wpartial-fields"
    - "-Wredundant-constraints"
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - text
    - integral-philosophy
    - hspec >= 2.7 && < 3
    - QuickCheck >= 2.13 && < 2.15
    ghc-options:
    - "-Wall"
    - "-Wcompat"
    - "-Widentities"
    - "-Wincomplete-record-updates"
    - "-Wincomplete-uni-patterns"
    - "-Wmissing-export-lists"
    - "-Wmissing-home-modules"
    - "-Wpartial-fields"
    - "-Wredundant-constraints"
    - "-O2"
    - "-threaded"
    - "-rtsopts"
    - "-with-rtsopts=-N"