<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:tei="http://www.tei-c.org/ns/1.0"
    xmlns="http://www.w3.org/1999/xhtml"
    exclude-result-prefixes="tei">

<xsl:output method="xml" 
    doctype-public="-//W3C//DTD XHTML 1.1//EN"
    doctype-system="http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"
    indent="yes" encoding="UTF-8"/>

<xsl:template match="/tei:TEI">
    <html xml:lang="{@xml:lang}">
        <head>
            <title><xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title"/></title>
            <meta charset="UTF-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <style>
                body { font-family: 'Georgia', serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
                .page { border-bottom: 2px solid #333; margin-bottom: 40px; padding-bottom: 20px; }
                .page-title { color: #2c3e50; border-bottom: 1px solid #3498db; padding-bottom: 10px; }
                .metadata { background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }
                .metadata p { margin: 5px 0; }
                .toc { background: #e3f2fd; padding: 20px; margin: 20px 0; border-radius: 5px; }
                .toc ul { list-style-type: none; padding-left: 0; }
                .toc li { margin: 5px 0; }
                .toc a { text-decoration: none; color: #1976d2; }
                .toc a:hover { text-decoration: underline; }
                h1, h2, h3, h4, h5, h6 { color: #2c3e50; }
                .formula { background: #f5f5f5; padding: 10px; border-radius: 3px; font-family: 'Courier New', monospace; }
                .quote { border-left: 4px solid #3498db; padding-left: 20px; margin: 20px 0; font-style: italic; }
                .code { background: #f8f9fa; padding: 10px; border-radius: 3px; font-family: 'Courier New', monospace; }
                .links { background: #e8f5e8; padding: 15px; border-radius: 5px; margin: 20px 0; }
                .links ul { list-style-type: disc; }
            </style>
        </head>
        <body>
            <header>
                <h1><xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title"/></h1>
                <p class="author">By <xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:author/tei:name"/></p>
                <p class="date"><xsl:value-of select="tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:date"/></p>
            </header>
            
            <xsl:if test="tei:text/tei:front">
                <section class="toc">
                    <h2>Table of Contents</h2>
                    <ul>
                        <xsl:for-each select="tei:text/tei:front//tei:div[@type='toc-entry']">
                            <li><a href="#{generate-id(.)}"><xsl:value-of select="tei:ref"/></a></li>
                        </xsl:for-each>
                    </ul>
                </section>
            </xsl:if>
            
            <main>
                <xsl:apply-templates select="tei:text/tei:body"/>
            </main>
            
            <footer>
                <p>Generated by Integral Philosophy Publishing System</p>
            </footer>
        </body>
    </html>
</xsl:template>

<xsl:template match="tei:div[@type='page']">
    <article class="page" id="{generate-id(.)}">
        <xsl:apply-templates/>
    </article>
</xsl:template>

<xsl:template match="tei:div[@type='metadata']">
    <div class="metadata">
        <xsl:apply-templates/>
    </div>
</xsl:template>

<xsl:template match="tei:div[@type='links']">
    <div class="links">
        <xsl:apply-templates/>
    </div>
</xsl:template>

<xsl:template match="tei:head">
    <h2 class="page-title"><xsl:value-of select="."/></h2>
</xsl:template>

<xsl:template match="tei:p[@type='url' or @type='language' or @type='description' or @type='keywords' or @type='scraped-date']">
    <p><xsl:value-of select="."/></p>
</xsl:template>

<xsl:template match="tei:p">
    <p><xsl:apply-templates/></p>
</xsl:template>

<xsl:template match="tei:ref">
    <a href="{@target}"><xsl:value-of select="."/></a>
</xsl:template>

<xsl:template match="tei:figure">
    <figure>
        <img src="{tei:graphic/@url}" alt="{tei:figDesc}"/>
        <figcaption><xsl:value-of select="tei:figDesc"/></figcaption>
    </figure>
</xsl:template>

<xsl:template match="tei:quote[@type='code']">
    <div class="code">
        <pre><xsl:value-of select="."/></pre>
    </div>
</xsl:template>

<xsl:template match="tei:formula">
    <div class="formula">
        <xsl:value-of select="."/>
    </div>
</xsl:template>

<xsl:template match="tei:list">
    <ul>
        <xsl:apply-templates/>
    </ul>
</xsl:template>

<xsl:template match="tei:item">
    <li><xsl:apply-templates/></li>
</xsl:template>

<xsl:template match="tei:quote">
    <blockquote class="quote">
        <xsl:apply-templates/>
    </blockquote>
</xsl:template>

<xsl:template match="tei:hi[@rend='bold']">
    <strong><xsl:apply-templates/></strong>
</xsl:template>

<xsl:template match="tei:hi[@rend='it']">
    <em><xsl:apply-templates/></em>
</xsl:template>

<xsl:template match="tei:hi[@rend='t']">
    <code><xsl:apply-templates/></code>
</xsl:template>

<xsl:template match="tei:span">
    <span><xsl:value-of select="."/></span>
</xsl:template>

</xsl:stylesheet>