xslt_transformer.XSLTTransformer Class Reference
Public Member Functions
__init__ (self, Optional[Union[str, Path]] xslt_dir=None)
bool transform_to_html (self, Union[str, Path] tei_file, Union[str, Path] output_file)
bool transform_to_latex (self, Union[str, Path] tei_file, Union[str, Path] output_file)
bool compile_latex_to_pdf (self, Union[str, Path] latex_file, Union[str, Path] output_file)
bool transform_to_epub (self, Union[str, Path] tei_file, Union[str, Path] output_file)
bool transform_to_docx (self, Union[str, Path] tei_file, Union[str, Path] output_file)
Dict[str, bool] transform_all_formats (self, Union[str, Path] tei_file, Union[str, Path] output_dir)
Public Attributes
xslt_dir = Path(xslt_dir) if xslt_dir else Path("xslt")
temp_dir = None
Protected Member Functions
None _create_xslt_stylesheets (self)
None _create_html_xslt (self)
None _create_latex_xslt (self)
None _create_epub_xslt (self)
None _create_docx_xslt (self)
Detailed Description
Handles XSLT transformations from TEI XML to multiple formats
Definition at line 23 of file xslt_transformer.py.
Constructor & Destructor Documentation
__init__()
xslt_transformer.XSLTTransformer.__init__ (self, Optional[Union[str, Path]] xslt_dir = None)
Definition at line 26 of file xslt_transformer.py.
Member Function Documentation
_create_docx_xslt()
 None xslt_transformer.XSLTTransformer._create_docx_xslt (self) [protected]
Create DOCX XSLT stylesheet (simplified)
Definition at line 462 of file xslt_transformer.py.
References xslt_dir.
Referenced by _create_xslt_stylesheets().
_create_epub_xslt()
 None xslt_transformer.XSLTTransformer._create_epub_xslt (self) [protected]
Create EPUB XSLT stylesheet
Definition at line 372 of file xslt_transformer.py.
References xslt_dir.
Referenced by _create_xslt_stylesheets().
_create_html_xslt()
 None xslt_transformer.XSLTTransformer._create_html_xslt (self) [protected]
Create HTML XSLT stylesheet
Definition at line 51 of file xslt_transformer.py.
References xslt_dir.
Referenced by _create_xslt_stylesheets().
_create_latex_xslt()
 None xslt_transformer.XSLTTransformer._create_latex_xslt (self) [protected]
Create LaTeX XSLT stylesheet
Definition at line 209 of file xslt_transformer.py.
References xslt_dir.
Referenced by _create_xslt_stylesheets().
_create_xslt_stylesheets()
 None xslt_transformer.XSLTTransformer._create_xslt_stylesheets (self) [protected]
Create XSLT stylesheets for different output formats
Definition at line 36 of file xslt_transformer.py.
References _create_docx_xslt(), _create_epub_xslt(), _create_html_xslt(), and _create_latex_xslt().
compile_latex_to_pdf()
 bool xslt_transformer.XSLTTransformer.compile_latex_to_pdf (self, Union[str, Path] latex_file, Union[str, Path] output_file)
Compile LaTeX to PDF
Definition at line 576 of file xslt_transformer.py.
Referenced by transform_all_formats().
transform_all_formats()
 Dict[str, bool] xslt_transformer.XSLTTransformer.transform_all_formats (self, Union[str, Path] tei_file, Union[str, Path] output_dir)
Transform TEI to all supported formats
Definition at line 744 of file xslt_transformer.py.
References compile_latex_to_pdf(), transform_to_docx(), transform_to_epub(), transform_to_html(), and transform_to_latex().
transform_to_docx()
 bool xslt_transformer.XSLTTransformer.transform_to_docx (self, Union[str, Path] tei_file, Union[str, Path] output_file)
Transform TEI to DOCX using external tools
Definition at line 707 of file xslt_transformer.py.
Referenced by transform_all_formats().
transform_to_epub()
 bool xslt_transformer.XSLTTransformer.transform_to_epub (self, Union[str, Path] tei_file, Union[str, Path] output_file)
Transform TEI to EPUB
Definition at line 618 of file xslt_transformer.py.
References transform_to_html().
Referenced by transform_all_formats().
transform_to_html()
 bool xslt_transformer.XSLTTransformer.transform_to_html (self, Union[str, Path] tei_file, Union[str, Path] output_file)
Transform TEI to HTML using XSLT
Definition at line 510 of file xslt_transformer.py.
References xslt_dir.
Referenced by transform_all_formats(), and transform_to_epub().
transform_to_latex()
 bool xslt_transformer.XSLTTransformer.transform_to_latex (self, Union[str, Path] tei_file, Union[str, Path] output_file)
Transform TEI to LaTeX using XSLT
Definition at line 546 of file xslt_transformer.py.
References xslt_dir.
Referenced by transform_all_formats().
Member Data Documentation
temp_dir
xslt_transformer.XSLTTransformer.temp_dir = None
Definition at line 28 of file xslt_transformer.py.
xslt_dir
xslt_transformer.XSLTTransformer.xslt_dir = Path(xslt_dir) if xslt_dir else Path("xslt")
Definition at line 27 of file xslt_transformer.py.
Referenced by _create_docx_xslt(), _create_epub_xslt(), _create_html_xslt(), _create_latex_xslt(), transform_to_html(), and transform_to_latex().
The documentation for this class was generated from the following file:
/home/domini/src/Magazine/Magazine/scripts/xslt_transformer.py